### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by gjgit** [williambout/react-native-proximity#10]
hi there every time i run my react native project getting this error 

![gj](https://user-images.githubusercontent.com/2841150/39005186-1e474fdc-441d-11e8-8cbc-c2a5b6add6c7.png)

**Comment by JoeDurand3** [comment]
The `react-native-proximity` project isn't being compiled. Add the following line to your `android/app/build.gradle` file:

```
dependencies {
    ...
    compile project(':react-native-proximity')
}
```

@williambout , can we fix the link step to include this dependency?
