### ISSUE TITLE
Android: Error:Execution failed for task ':react-native-proximity:compileReleaseJavaWithJavac'. 

### ISSUE THREAD

**Issue by pratih** [williambout/react-native-proximity#7]
Hello, thanks for the great RN module.

I'm able to use in iOS but have an issue with Android.

node_modules/react-native-proximity/android/src/main/java/com/RNProximity/RNProximityPackage.java

Error:(19, 5) error: method does not override or implement a method from a supertype

Error:Execution failed for task ':react-native-proximity:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Thank you for taking the time to take a look at the issue.

**Comment by jay1337** [comment]
@pratih just delete lines:

```
    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }
```

**Comment by williambout** [comment]
This has been fixed with https://github.com/williambout/react-native-proximity/pull/8
